# Generated by Django 5.1.6 on 2025-04-15 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_movie_release_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1899), django.core.validators.MaxValueValidator(2100)])),
                ('why_suggested', models.TextField()),
                ('suggestion_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
